/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include <string>
/* Header for class orbotix_unity_UnityBridge */

#ifndef _Included_orbotix_unity_UnityBridge
#define _Included_orbotix_unity_UnityBridge
#ifdef __cplusplus
extern "C" {
#endif

typedef void (*ReceiveDeviceMessageCallback)(const char *);
ReceiveDeviceMessageCallback unityMessageCallback;

  /*
   * Class:     orbotix_unity_UnityBridge
   * Method:    _RegisterRecieveDeviceMessageCallback
   * Signature: ()V
   */
void _RegisterRecieveDeviceMessageCallback(ReceiveDeviceMessageCallback callback);
  
/*
 * Class:     orbotix_unity_UnityBridge
 * Method:    sendMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_orbotix_unity_UnityBridge_sendMessage
  (JNIEnv *env, jobject object, jstring msg);

#ifdef __cplusplus
}
#endif
#endif